recycler view added
MUSoC/Location-based-tools-android pull request #1
Opened 2017-06-13 12:32 UTC by manya-19

2017-06-13 12:35 UTC, kartikarora commented on Locationapp/.gitignore
> +*.iml
Consider adding the entire `.idea` folder to .gitignore

Then run

```git
git rm -r --cached *
git add --all
git commit -m <commit_message>
git push origin master
```

2017-06-13 12:38 UTC, kartikarora commented on Locationapp/app/src/main/java/com/example/manya/locationapp/MainActivity.java
> +    private PlacesListAdapter Adapter;
Readup [this](https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md) for naming and code guidelines.

2017-06-13 12:39 UTC, kartikarora reviewed
@sakethkaparthi I've added a few comments on the commit,if you don't mind? I can remove them if you have an issue!

2017-06-14 13:53 UTC, sakethkaparthi requested changes
@manya-19 please consider the things mentioned above by @kartikarora and make the changes

2017-06-17 07:04 UTC, sakethkaparthi approved these changes

2017-06-17 07:04 UTC, merged